name        'puppet-wpcli'
version     '0.0.1'
source      'https://github.com/AppliedTrust/puppet-wpcli.git'
license     'Apache License, Version 2.0'
summary     'wp-cli module for Puppet'
description 'Puppet module enabling the installation and setup of wp-cli'
